### ISSUE TITLE
ValueError while running combine_counts.py

### ISSUE THREAD

**Issue by Schahrjar** [mdanzi/Fazal2020Scripts#1]
Running the `combine_counts.py` script on EH de novo output of thousands of exomes returned this error on one of the samples:

`Traceback (most recent call last):
  File "/data/hestia/shejazi/repeat-expansion/PhD_project/Fazal2020Scripts-master/EHDn-v0.6.2_HelperScripts/combine_counts.py", line 168, in <module>
    main()
  File "/data/hestia/shejazi/repeat-expansion/PhD_project/Fazal2020Scripts-master/EHDn-v0.6.2_HelperScripts/combine_counts.py", line 161, in main
    combined_regions = process_samples(parameters, samples, sample_depths)
  File "/data/hestia/shejazi/repeat-expansion/PhD_project/Fazal2020Scripts-master/EHDn-v0.6.2_HelperScripts/combine_counts.py", line 107, in process_samples
    process_sample(parameters, denovo_json, sample.id,
  File "/data/hestia/shejazi/repeat-expansion/PhD_project/Fazal2020Scripts-master/EHDn-v0.6.2_HelperScripts/combine_counts.py", line 84, in process_sample
    current_regions = regiontools.create_region_collection_from_denovo_record(
  File "/data/hestia/shejazi/repeat-expansion/PhD_project/Fazal2020Scripts-master/EHDn-v0.6.2_HelperScripts/core/regiontools.py", line 178, in create_region_collection_from_denovo_record
    region = create_region_from_denovo_record(sample_id, region_count)
  File "/data/hestia/shejazi/repeat-expansion/PhD_project/Fazal2020Scripts-master/EHDn-v0.6.2_HelperScripts/core/regiontools.py", line 169, in create_region_from_denovo_record
    chrom, start, end = region_encoding
ValueError: too many values to unpack (expected 3)
`

I couldn't find the cause and finally removed that sample from my `manifest.txt` file. After rerunning the code, I got the same error on few other samples and I did the same for that samples. I got the output `EHDnResults.combinedCounts.json` file at the end; but interested to know what was the cause.

Thanks!

**Comment by sxf710** [comment]
HI, we haven't seen this error when running samples so it might be something specific to do with the samples you have. This script was actually written by Egor Dolzhenko (the developer of ExpansionHunter Denovo), so you might want to reach out to him about it.
